### ISSUE TITLE
`SliderInput` doesn't set precision correctly

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/pcui#16] opened 2020-10-13 10:26 UTC
Specifying precision to the pcui.SliderInput constructor appears to work, but setting precision after construction doesn't.

(@slimbuck: Actually it turns out you must do both for precision to work: specify precision at construction and then set it afterwards as well.)

**Comment by ellthompson** [comment] 2023-01-19 16:39
I can't reproduce this in the current version of PCUI so closing the issue.

**Closed by ellthompson** 2023-01-19 16:39 UTC
Labels: bug
