### ISSUE TITLE
Sidebar/Panel resizing is buggy on mobile devices

### ISSUE THREAD

**Issue by WaelShaikh** [playcanvas/pcui#14] opened 2020-10-12 10:56 UTC
If you resize the sidebar panel in the PlayCanvas editor as well as in the PlayCanvas Viewer once, then lift your finger and interact with another component the panel that you resized continues to resize even though you are no longer interacting with it.

**Steps to reproduce the behavior:**
1. Go to https://playcanvas.com/viewer on a mobile device
2. Expand the sidebar
3. Resize it
4. Lift your finger to stop resizing
5. Then move your finger in either the Viewport or inside the sidebar (You need to move your finger not just tap it)
6. The sidebar will resize to where your finger is

**Expected behavior**

Once you lift your finger, the panel should stop resizing.

**Smartphone:**
 - Device: Xioami Redmi Note 8 Pro
 - OS: Android 10
 - Browser: Microsoft Edge, Google Chrome

**Additional Context:**
This is the biggest issue I faced while using the editor on my phone. Fixing this might make the editor finally usable on mobile devices.

**Comment by willeastcott** [comment] 2021-02-16 00:41
Just FYI, I am unable to reproduce this on iOS 14.4. Presumably an Android-specific bug.

**Comment by Maksims** [comment] 2021-02-16 09:02
Can confirm, on Android Chrome, resizing panel is "sticky".

**Comment by willeastcott** [comment] 2021-02-16 10:35
OK. Well, if it's Android only, I'll assign to @vkalpias since I know he has an Android device. 😄

**Comment by willeastcott** [comment] 2024-12-26 18:17
Tested on a Google Pixel 7a running Android 15 with Chrome. Works as expected. Closing.

**Closed by willeastcott** 2024-12-26 18:17 UTC
Labels: bug
